import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
const testDir = dirname(fileURLToPath(import.meta.url)); const repoDir = join(testDir, "..", "..");
function load(){ const sandbox={console,window:{}}; sandbox.globalThis=sandbox.window; vm.createContext(sandbox); vm.runInContext(readFileSync(join(repoDir,"relatorio-qualidade-obras","elo-executive-budget-engine.js"),"utf8"),sandbox); return sandbox.window.EloExecutiveBudgetEngine; }
test("ExecutiveBudget bloqueia executivo sem cidade composicoes fechadas e quantitativos completos",()=>{ const e=load(); const result=e.evaluateExecutiveReadiness({project:{type:"casa_terrea",builtAreaM2:80},premises:{},workPackages:[{status:"pending"}],compositionSelections:[]},{budgetTable:{summary:{pendingRows:4},rows:[]}}); assert.equal(result.ready,false); assert.ok(result.blockers.some(x=>x.id==="city_uf")); assert.ok(result.blockers.some(x=>x.id==="candidate_compositions")); });
test("ExecutiveBudget score aumenta quando dados sao preenchidos",()=>{ const e=load(); const low=e.evaluateExecutiveReadiness({project:{builtAreaM2:80},premises:{},workPackages:[{status:"pending"}],compositionSelections:[]},{budgetTable:{summary:{pendingRows:3},rows:[]}}); const high=e.evaluateExecutiveReadiness({client:{name:"Cliente"},project:{name:"Obra",cityUf:"Salvador/BA",type:"casa_terrea",builtAreaM2:80},premises:{sinapiState:"BA",sinapiReferenceMonth:"2026-06",priceSource:"SINAPI",bdi:20},workPackages:[{status:"ready"}],compositionSelections:[{selected:true}]},{budgetTable:{summary:{pendingRows:0},rows:[]},consumptionBlocked:[]}); assert.ok(high.score>low.score); });

test("ExecutiveChecklist bloqueia fechamento sem dados obrigatorios",()=>{ const e=load(); const result=e.buildExecutiveClosingChecklist({project:{type:"casa_terrea"},premises:{},workPackages:[{status:"pending"}],compositionSelections:[],revisions:[]},{budgetTable:{summary:{pendingRows:2}},baseStatus:{loaded:false},compositionMatches:[{found:true}]}); assert.equal(result.canClose,false); assert.ok(result.blockers.some(x=>x.id==="city_uf")); assert.ok(result.blockers.some(x=>x.id==="compositions")); assert.ok(result.blockers.some(x=>x.id==="prices")); });



test("ExecutiveClosing bloqueia candidatas pre?o e BDI ausentes",()=>{ const e=load(); const budget={budgetTable:{summary:{pendingRows:0},rows:[{serviceId:"piso",service:"Piso",quantity:50,unit:"m2",compositionCode:"SINAPI",consumptionStatus:"ready"}]},compositionMatches:[{serviceId:"piso",found:true}],priceStatus:{pricedRows:[],missingPrices:[{service:"Piso"}]}}; const result=e.prepareExecutiveClosing({project:{name:"Casa",cityUf:"Salvador/BA"},premises:{},compositionSelections:[]},budget,{requireBdi:true}); assert.equal(result.canClose,false); assert.ok(result.blockers.some((item)=>item.id==="candidate_compositions")); assert.ok(result.blockers.some((item)=>item.id==="prices")); assert.ok(result.blockers.some((item)=>item.id==="bdi")); });

test("ExecutiveClosing bloqueia linha s? com checklist completo",()=>{ const e=load(); const denied=e.lockExecutiveRow({id:"p1"},"row_1",{checks:{quantityConfirmed:true}}); assert.equal(denied.lockError,"row_checklist_not_ok"); const locked=e.lockExecutiveRow({id:"p1",revisions:[],history:[]},"row_1",{checks:{quantityConfirmed:true,compositionSelected:true,priceValidated:true,premisesConfirmed:true,unitCompatible:true}}); assert.equal(locked.lockedRows[0].rowId,"row_1"); assert.equal(locked.revisions.length,1); });

test("ExecutiveBudget V3 estrutura casa 70m2 sem calcular valores",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"casa_terrea",city:"Salvador",state:"BA",builtAreaM2:70,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto armado",roofType:"telha ceramica",foundationType:"sapata"}}); assert.equal(result.prontoParaCalculo,true); assert.equal(result.etapas.length,13); assert.ok(result.etapas.some((stage)=>stage.id==="fundacao")); assert.ok(result.etapas.some((stage)=>stage.id==="administracao")); assert.equal(result.etapas.find((stage)=>stage.id==="estrutura").dependeDe[0],"fundacao"); assert.equal(result.pendencias.length,0); assert.equal(result.etapas.find((stage)=>stage.id==="fundacao").status,"parcial"); });

test("ExecutiveBudget V3 estrutura casa 120m2 com disciplinas automaticas",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"casa_terrea",cityUf:"Vitoria da Conquista/BA",builtAreaM2:120,floors:1,standard:"alto",ceilingHeightM:3,structuralType:"concreto armado",roofType:"laje impermeabilizada",foundationType:"radier"}}); const ids=result.etapas.map((stage)=>stage.id); assert.equal(result.prontoParaCalculo,true); assert.deepEqual(["fundacao","estrutura","alvenaria","cobertura","instalacoes_hidraulicas","instalacoes_eletricas","revestimentos","pintura","esquadrias","loucas","metais","urbanizacao","administracao"].every((id)=>ids.includes(id)),true); assert.equal(result.projeto.city,"Vitoria da Conquista"); assert.equal(result.projeto.state,"BA"); });

test("ExecutiveBudget V3 sobrado infere dois pavimentos",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"sobrado",city:"Feira de Santana",state:"BA",builtAreaM2:140,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto armado",roofType:"telha fibrocimento",foundationType:"sapata corrida"}}); assert.equal(result.projeto.floors,2); assert.equal(result.prontoParaCalculo,true); assert.ok(result.etapas.find((stage)=>stage.id==="estrutura").servicos.includes("escadas")); });

test("ExecutiveBudget V3 bloqueia casa sem fundacao informada",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"casa_terrea",city:"Salvador",state:"BA",builtAreaM2:70,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto armado",roofType:"telha ceramica"}}); assert.equal(result.prontoParaCalculo,false); assert.ok(result.pendencias.some((item)=>item.id==="foundationType")); assert.notEqual(result.etapas.find((stage)=>stage.id==="fundacao").status,"completa"); });

test("ExecutiveBudget V3 bloqueia casa sem cidade",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"casa_terrea",state:"BA",builtAreaM2:70,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto armado",roofType:"telha ceramica",foundationType:"sapata"}}); assert.equal(result.prontoParaCalculo,false); assert.ok(result.pendencias.some((item)=>item.id==="city")); assert.equal(result.premissas.find((item)=>item.id==="city").ok,false); });

test("ExecutiveBudget V3 bloqueia casa sem padrao",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"casa_terrea",city:"Salvador",state:"BA",builtAreaM2:70,floors:1,ceilingHeightM:2.8,structuralType:"concreto armado",roofType:"telha ceramica",foundationType:"sapata"}}); assert.equal(result.prontoParaCalculo,false); assert.ok(result.pendencias.some((item)=>item.id==="standard")); assert.ok(result.checklist.some((item)=>item.status==="parcial"||item.status==="nao_iniciada")); });

test("ExecutiveBudget V3.1 knowledge graph expõe nós e relações",()=>{ const e=load(); const graph=e.buildKnowledgeGraph(); assert.equal(graph.nodes.length,13); assert.ok(graph.relations.length>=12); assert.ok(graph.nodes.find((node)=>node.id==="fundacao").servicosPrincipais.includes("sapatas")); assert.ok(graph.nodes.find((node)=>node.id==="alvenaria").servicosPrincipais.includes("vergas")); assert.equal(graph.extensionPoints.sinapi.ready,false); assert.equal(graph.extensionPoints.cronograma.kind,"schedule_engine"); });

test("ExecutiveBudget V3.1 resolve dependências de casa térrea",()=>{ const e=load(); const ids=e.resolveDependencies({project:{type:"casa_terrea"}}); assert.equal(JSON.stringify(ids.slice(0,4)),JSON.stringify(["fundacao","estrutura","alvenaria","cobertura"])); assert.ok(ids.includes("instalacoes_hidraulicas")); assert.ok(ids.includes("revestimentos")); assert.ok(ids.includes("pintura")); });

test("ExecutiveBudget V3.1 resolve sobrado com estrutura antes de alvenaria",()=>{ const e=load(); const ids=e.resolveDependencies({project:{type:"sobrado"}}); assert.ok(ids.indexOf("fundacao")<ids.indexOf("estrutura")); assert.ok(ids.indexOf("estrutura")<ids.indexOf("alvenaria")); assert.ok(ids.includes("cobertura")); });

test("ExecutiveBudget V3.1 valida projeto sem fundação",()=>{ const e=load(); const result=e.validateExecutiveProject({project:{city:"Salvador",state:"BA",builtAreaM2:90,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto",roofType:"telha",foundationType:"sapata"},disciplines:["estrutura","alvenaria","cobertura"]}); assert.equal(result.valid,false); assert.ok(result.disciplinasAusentes.includes("fundacao")); assert.ok(result.dependenciasQuebradas.some((item)=>item.id==="broken_estrutura_fundacao")); });

test("ExecutiveBudget V3.1 valida projeto sem estrutura",()=>{ const e=load(); const result=e.validateExecutiveProject({project:{city:"Salvador",state:"BA",builtAreaM2:90,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto",roofType:"telha",foundationType:"sapata"},disciplines:["fundacao","alvenaria","cobertura"]}); assert.equal(result.valid,false); assert.ok(result.disciplinasAusentes.includes("estrutura")); assert.ok(result.dependenciasQuebradas.some((item)=>item.id==="broken_alvenaria_estrutura")); });

test("ExecutiveBudget V3.1 valida projeto sem cobertura",()=>{ const e=load(); const result=e.validateExecutiveProject({project:{city:"Salvador",state:"BA",builtAreaM2:90,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto",roofType:"telha",foundationType:"sapata"},disciplines:["fundacao","estrutura","alvenaria","revestimentos","pintura"]}); assert.equal(result.valid,false); assert.ok(result.disciplinasAusentes.includes("cobertura")); });

test("ExecutiveBudget V3.1 bloqueia pintura antes do reboco",()=>{ const e=load(); const result=e.validateExecutiveProject({project:{city:"Salvador",state:"BA",builtAreaM2:90,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto",roofType:"telha",foundationType:"sapata"},stageOrder:["fundacao","estrutura","alvenaria","pintura","revestimentos"]}); assert.equal(result.valid,false); assert.ok(result.ordemIncorreta.some((item)=>item.id==="order_revestimentos_instalacoes_hidraulicas")||result.ordemIncorreta.some((item)=>item.id==="order_pintura_revestimentos")); assert.ok(result.errors.some((item)=>/pintura|revestimentos/.test(item.id))); });

test("ExecutiveBudget V3.1 valida projeto completo e explica dependências",()=>{ const e=load(); const project={city:"Salvador",state:"BA",builtAreaM2:120,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto",roofType:"telha",foundationType:"sapata"}; const disciplines=e.resolveDependencies({project}); const result=e.validateExecutiveProject({project,disciplines}); const reasons=e.explainDependencies({disciplines}); assert.equal(result.valid,true); assert.ok(reasons.some((text)=>text.includes("cobertura depende"))); assert.ok(reasons.some((text)=>text.includes("pintura depende"))); });
function completeV32Project(overrides={}){ return Object.assign({type:"casa_terrea",city:"Salvador",state:"BA",builtAreaM2:70,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto armado",roofType:"telha ceramica",foundationType:"sapata"},overrides); }
function completeV32Geometry(overrides={}){ return Object.assign({perimeterM:34,wallThicknessM:0.14,roofSlopePercent:30,openingsAreaM2:8},overrides); }
function stageById(result,id){ return result.stages.find((stage)=>stage.id===id); }
function quantityById(stage,id){ return stage.quantitativos.find((item)=>item.id===id); }

test("ExecutiveBudget V3.2 GeometryModel casa 70m2",()=>{ const e=load(); const result=e.buildGeometryModel({project:completeV32Project(),geometry:completeV32Geometry()}); assert.equal(result.builtAreaM2,70); assert.equal(result.perimeterM,34); assert.equal(result.ceilingHeightM,2.8); assert.equal(result.wallThicknessM,0.14); assert.equal(result.floors,1); assert.equal(result.roofAreaM2,91); assert.equal(result.heightTotalM,2.8); assert.equal(result.pendencias.length,0); });

test("ExecutiveBudget V3.2 gera quantitativos para casa 120m2",()=>{ const e=load(); const result=e.buildAutomaticQuantities({project:completeV32Project({builtAreaM2:120}),geometry:completeV32Geometry({perimeterM:46,roofSlopePercent:25,openingsAreaM2:12})}); assert.equal(result.readyForPricing,true); assert.equal(stageById(result,"fundacao").quantitativos.length,5); assert.equal(stageById(result,"estrutura").quantitativos.length,3); assert.equal(stageById(result,"alvenaria").quantitativos.length,6); assert.equal(stageById(result,"cobertura").quantitativos.length,7); assert.equal(stageById(result,"revestimentos").quantitativos.length,5); assert.equal(stageById(result,"pintura").quantitativos.length,3); assert.ok(quantityById(stageById(result,"alvenaria"),"blocos").quantidade>0); });

test("ExecutiveBudget V3.2 sobrado usa altura total e pavimentos",()=>{ const e=load(); const result=e.buildAutomaticQuantities({project:completeV32Project({type:"sobrado",builtAreaM2:140,floors:2}),geometry:completeV32Geometry({perimeterM:40,roofAreaM2:160})}); const model=result.geometryModel; const wallArea=quantityById(stageById(result,"alvenaria"),"area_paredes"); assert.equal(model.heightTotalM,5.6); assert.equal(wallArea.quantidade,216); assert.ok(quantityById(stageById(result,"estrutura"),"volume_concreto").quantidade>30); });

test("ExecutiveBudget V3.2 cobertura desconhecida fica parcial",()=>{ const e=load(); const result=e.buildAutomaticQuantities({project:completeV32Project({roofType:""}),geometry:completeV32Geometry()}); const cobertura=stageById(result,"cobertura"); assert.equal(result.readyForPricing,false); assert.equal(cobertura.status,"parcial"); assert.ok(cobertura.pendencias.some((item)=>item.id==="roofType")); assert.equal(cobertura.quantitativos.length,0); });

test("ExecutiveBudget V3.2 sem pe-direito retorna pendencia",()=>{ const e=load(); const result=e.buildAutomaticQuantities({project:completeV32Project({ceilingHeightM:0}),geometry:completeV32Geometry()}); assert.ok(result.geometryModel.pendencias.some((item)=>item.id==="ceilingHeightM")); assert.equal(stageById(result,"alvenaria").status,"parcial"); assert.equal(stageById(result,"pintura").status,"parcial"); });

test("ExecutiveBudget V3.2 sem espessura de parede bloqueia alvenaria",()=>{ const e=load(); const result=e.buildAutomaticQuantities({project:completeV32Project(),geometry:completeV32Geometry({wallThicknessM:0})}); const alvenaria=stageById(result,"alvenaria"); assert.equal(alvenaria.status,"parcial"); assert.ok(alvenaria.pendencias.some((item)=>item.id==="wallThicknessM")); assert.equal(alvenaria.quantitativos.length,0); });

test("ExecutiveBudget V3.2 projeto completo preserva estrutura executiva",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:completeV32Project({builtAreaM2:120}),geometry:completeV32Geometry({perimeterM:46,roofAreaM2:145})}); assert.equal(result.quantitativosAutomaticos.readyForPricing,true); assert.equal(result.geometryModel.roofAreaM2,145); assert.equal(result.quantitativosAutomaticos.extensionPoints.sinapi.ready,false); assert.equal(result.quantitativosAutomaticos.extensionPoints.custos.kind,"cost_engine"); });

test("ExecutiveBudget V3.2 rastreia origem dos quantitativos",()=>{ const e=load(); const result=e.buildAutomaticQuantities({project:completeV32Project(),geometry:completeV32Geometry()}); const reboco=quantityById(stageById(result,"revestimentos"),"reboco"); const tinta=quantityById(stageById(result,"pintura"),"tinta"); assert.ok(reboco.origemCalculo.includes("2 faces")); assert.ok(tinta.origemCalculo.includes("reboco")); assert.ok(reboco.premissasUtilizadas.includes("openingsAreaM2")); });
function issueByRule(result,rule){ return result.issues.find((item)=>item.rule===rule); }
function checklistById(result,id){ return result.checklist.find((item)=>item.id===id); }

test("ExecutiveBudget V3.3 rules engine valida casa correta",()=>{ const e=load(); const result=e.validateEngineeringRules({project:completeV32Project(),geometry:completeV32Geometry()}); assert.equal(result.valid,true); assert.equal(result.readyForCost,true); assert.equal(result.rulesApplied.length,16); assert.equal(checklistById(result,"fundacao").status,"OK"); assert.equal(checklistById(result,"pintura").readyForCost,true); });

test("ExecutiveBudget V3.3 bloqueia casa sem fundacao",()=>{ const e=load(); const result=e.validateEngineeringRules({project:completeV32Project({foundationType:""}),geometry:completeV32Geometry()}); assert.equal(result.valid,false); assert.equal(result.readyForCost,false); assert.equal(checklistById(result,"fundacao").status,"ERRO"); assert.ok(issueByRule(result,"foundation_required").correction.includes("fundacao")); });

test("ExecutiveBudget V3.3 bloqueia casa sem cobertura",()=>{ const e=load(); const result=e.validateEngineeringRules({project:completeV32Project({roofType:""}),geometry:completeV32Geometry({roofAreaM2:0,roofSlopePercent:0})}); assert.equal(result.valid,false); assert.equal(checklistById(result,"cobertura").status,"ERRO"); assert.ok(issueByRule(result,"roof_compatible").consequence.includes("Telhas")); });

test("ExecutiveBudget V3.3 detecta projeto fora de ordem",()=>{ const e=load(); const result=e.validateEngineeringRules({project:completeV32Project(),geometry:completeV32Geometry(),stageOrder:["fundacao","estrutura","alvenaria","pintura","revestimentos"]}); assert.equal(result.valid,false); assert.equal(checklistById(result,"pintura").status,"ERRO"); assert.ok(issueByRule(result,"painting_after_reboco").reason.includes("reboco")); });

test("ExecutiveBudget V3.3 alerta esquadrias antes da alvenaria",()=>{ const e=load(); const result=e.validateEngineeringRules({project:completeV32Project(),geometry:completeV32Geometry(),stageOrder:["fundacao","estrutura","esquadrias","alvenaria","cobertura","instalacoes_hidraulicas","instalacoes_eletricas","revestimentos","pintura"]}); assert.equal(checklistById(result,"esquadrias").status,"ALERTA"); assert.equal(issueByRule(result,"frames_after_masonry").severity,"ALERTA"); });

test("ExecutiveBudget V3.3 bloqueia estrutura sem pilares",()=>{ const e=load(); const result=e.validateEngineeringRules({project:completeV32Project(),geometry:completeV32Geometry(),stages:{estrutura:{servicos:["vigas","lajes"]}}}); assert.equal(result.valid,false); assert.equal(checklistById(result,"estrutura").status,"ERRO"); assert.ok(issueByRule(result,"structure_requires_pillars").correction.includes("pilares")); });

test("ExecutiveBudget V3.3 detecta projeto inconsistente",()=>{ const e=load(); const result=e.validateEngineeringRules({project:completeV32Project({builtAreaM2:-10,ceilingHeightM:2.1,floors:0}),geometry:completeV32Geometry({perimeterM:0,wallThicknessM:0,roofSlopePercent:0,roofAreaM2:0})}); assert.equal(result.valid,false); assert.ok(issueByRule(result,"area_positive")); assert.ok(issueByRule(result,"minimum_ceiling_height")); assert.ok(issueByRule(result,"walls_existing")); assert.ok(result.issues.filter((item)=>item.severity==="ERRO").length>=5); });

test("ExecutiveBudget V3.3 projeto completo fica apto para custos",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:completeV32Project({builtAreaM2:120}),geometry:completeV32Geometry({perimeterM:46,roofAreaM2:145})}); assert.equal(result.readyForCost,false); assert.equal(result.engineeringRules.readyForCost,true); assert.equal(result.engineeringRules.valid,true); assert.equal(result.engineeringRules.checklist.every((item)=>item.readyForCost),true); });
function officialRowsV34(){ return [
  {source:"SINAPI",compositionCode:"SINAPI-FUND-ESC",compositionName:"Escavacao manual de vala para fundacao",compositionUnit:"m3",serviceType:"escavacao",coefficient:1,inputs:[{inputCode:"88316",inputName:"SERVENTE COM ENCARGOS COMPLEMENTARES",inputUnit:"h",coefficient:1.2}]},
  {source:"SINAPI",compositionCode:"SINAPI-FUND-CONC",compositionName:"Concreto para sapata e baldrame",compositionUnit:"m3",serviceType:"concreto_fundacao",coefficient:1,inputs:[{inputCode:"CONC",inputName:"Concreto usinado",inputUnit:"m3",coefficient:1}]},
  {source:"SINAPI",compositionCode:"SINAPI-EST-CONC",compositionName:"Concreto armado para pilares vigas e lajes",compositionUnit:"m3",serviceType:"concreto_estrutural",coefficient:1,inputs:[{inputCode:"PED",inputName:"PEDREIRO COM ENCARGOS COMPLEMENTARES",inputUnit:"h",coefficient:0.8},{inputCode:"CONC",inputName:"Concreto",inputUnit:"m3",coefficient:1}]},
  {source:"ORSE",compositionCode:"ORSE-EST-MET",compositionName:"Estrutura metalica para cobertura e galpao",compositionUnit:"kg",serviceType:"estrutura_metalica",coefficient:1,inputs:[{inputCode:"ACO",inputName:"Perfil metalico",inputUnit:"kg",coefficient:1}]},
  {source:"SINAPI",compositionCode:"SINAPI-ALV-CER",compositionName:"Alvenaria de vedacao com bloco ceramico 14x19x29 cm",compositionUnit:"m2",serviceType:"alvenaria",coefficient:1,inputs:[{inputCode:"BLOCO",inputName:"Bloco ceramico",inputUnit:"un",coefficient:13.5},{inputCode:"PED",inputName:"PEDREIRO COM ENCARGOS COMPLEMENTARES",inputUnit:"h",coefficient:0.62}]},
  {source:"SINAPI",compositionCode:"SINAPI-ALV-CONC",compositionName:"Alvenaria de vedacao com bloco de concreto",compositionUnit:"m2",serviceType:"alvenaria",coefficient:1,inputs:[{inputCode:"BLOCOC",inputName:"Bloco de concreto",inputUnit:"un",coefficient:12}]},
  {source:"SINAPI",compositionCode:"SINAPI-COB-CER",compositionName:"Telhamento com telha ceramica sobre estrutura de madeira",compositionUnit:"m2",serviceType:"cobertura",coefficient:1,inputs:[{inputCode:"TELHA",inputName:"Telha ceramica",inputUnit:"un",coefficient:16}]},
  {source:"ORSE",compositionCode:"ORSE-CHAP",compositionName:"Chapisco aplicado em alvenaria",compositionUnit:"m2",serviceType:"chapisco",coefficient:1,inputs:[{inputCode:"CIM",inputName:"Cimento",inputUnit:"kg",coefficient:2.4}]},
  {source:"SINAPI",compositionCode:"SINAPI-REBOCO",compositionName:"Emboco ou massa unica em argamassa",compositionUnit:"m2",serviceType:"reboco",coefficient:1,inputs:[{inputCode:"AREIA",inputName:"Areia media",inputUnit:"m3",coefficient:0.025}]},
  {source:"SINAPI",compositionCode:"SINAPI-TINTA",compositionName:"Pintura com tinta latex acrilica em parede",compositionUnit:"m2",serviceType:"pintura",coefficient:1,inputs:[{inputCode:"PINT",inputName:"PINTOR COM ENCARGOS COMPLEMENTARES",inputUnit:"h",coefficient:0.2},{inputCode:"TINTA",inputName:"Tinta latex",inputUnit:"l",coefficient:0.18}]}
]; }

test("ExecutiveBudget V3.4 resolve composicao oficial de fundacao",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project(),geometry:completeV32Geometry()}); const result=e.resolveOfficialCompositions("fundacao",stageById(q,"fundacao").quantitativos,{foundationType:"sapata"},{officialBaseRows:officialRowsV34()}); assert.ok(result.compositions.some((item)=>item.codigo==="SINAPI-FUND-ESC")); assert.ok(result.compositions.some((item)=>item.codigo==="SINAPI-FUND-CONC")); assert.equal(result.compositions[0].origem,"SINAPI"); });

test("ExecutiveBudget V3.4 escolhe estrutura conforme premissa",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project({structuralType:"estrutura metalica"}),geometry:completeV32Geometry()}); const result=e.resolveOfficialCompositions("estrutura",stageById(q,"estrutura").quantitativos,{structuralType:"estrutura metalica"},{officialBaseRows:officialRowsV34()}); assert.ok(result.compositions.some((item)=>item.codigo==="ORSE-EST-MET")); assert.equal(result.compositions.some((item)=>item.codigo==="SINAPI-EST-CONC"),false); });

test("ExecutiveBudget V3.4 escolhe alvenaria por tipo de bloco",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project({blockType:"bloco ceramico"}),geometry:completeV32Geometry()}); const result=e.resolveOfficialCompositions("alvenaria",stageById(q,"alvenaria").quantitativos,{blockType:"bloco ceramico"},{officialBaseRows:officialRowsV34()}); const alv=result.compositions.find((item)=>item.quantityId==="area_paredes"); assert.equal(alv.codigo,"SINAPI-ALV-CER"); assert.ok(alv.insumos.some((item)=>item.descricao.includes("Bloco"))); assert.ok(alv.maoDeObra.some((item)=>item.descricao.includes("PEDREIRO"))); });

test("ExecutiveBudget V3.4 resolve cobertura sem misturar estrutura metalica",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project({roofType:"telha ceramica"}),geometry:completeV32Geometry()}); const result=e.resolveOfficialCompositions("cobertura",stageById(q,"cobertura").quantitativos,{roofType:"telha ceramica"},{officialBaseRows:officialRowsV34()}); assert.ok(result.compositions.some((item)=>item.codigo==="SINAPI-COB-CER")); assert.equal(result.compositions.some((item)=>item.codigo==="ORSE-EST-MET"),false); });

test("ExecutiveBudget V3.4 resolve revestimentos",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project(),geometry:completeV32Geometry()}); const result=e.resolveOfficialCompositions("revestimentos",stageById(q,"revestimentos").quantitativos,{}, {officialBaseRows:officialRowsV34()}); assert.ok(result.compositions.some((item)=>item.codigo==="ORSE-CHAP")); assert.ok(result.compositions.some((item)=>item.codigo==="SINAPI-REBOCO")); });

test("ExecutiveBudget V3.4 resolve pintura com rastreabilidade",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project(),geometry:completeV32Geometry()}); const result=e.resolveOfficialCompositions("pintura",stageById(q,"pintura").quantitativos,{}, {officialBaseRows:officialRowsV34()}); const tinta=result.compositions.find((item)=>item.codigo==="SINAPI-TINTA"); assert.equal(tinta.unidade,"m2"); assert.ok(tinta.motivoEscolha.includes("pintura")); assert.equal(tinta.precoUnitario,undefined); });

test("ExecutiveBudget V3.4 nao inventa composicao inexistente",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project(),geometry:completeV32Geometry()}); const result=e.resolveOfficialCompositions("pintura",stageById(q,"pintura").quantitativos,{}, {officialBaseRows:[]}); assert.equal(result.compositions.length,0); assert.ok(result.pendencias.some((item)=>item.id==="official_base_missing")); });

test("ExecutiveBudget V3.4 marca composicao ambigua",()=>{ const e=load(); const q=e.buildAutomaticQuantities({project:completeV32Project(),geometry:completeV32Geometry()}); const rows=[{source:"SINAPI",compositionCode:"SINAPI-ALV-A",compositionName:"Alvenaria de vedacao com bloco",compositionUnit:"m2",serviceType:"alvenaria"},{source:"ORSE",compositionCode:"ORSE-ALV-B",compositionName:"Alvenaria de vedacao com bloco",compositionUnit:"m2",serviceType:"alvenaria"}]; const result=e.resolveOfficialCompositions("alvenaria",stageById(q,"alvenaria").quantitativos,{}, {officialBaseRows:rows}); assert.equal(result.compositions.length,0); assert.ok(result.pendencias.some((item)=>/ambiguous/.test(item.id))); });
function disciplineIds(result){ return result.etapas.map((stage)=>stage.id); }

test("ExecutiveBudget V3.5 classifica residencia nova e preserva motor residencial",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:completeV32Project({type:"casa_terrea"}),geometry:completeV32Geometry(),officialBaseRows:officialRowsV34()}); const ids=disciplineIds(result); assert.equal(result.typologyRouting.typology,"residencia_nova"); assert.ok(ids.includes("fundacao")); assert.ok(ids.includes("loucas")); assert.ok(ids.includes("metais")); assert.equal(result.typologyRouting.readyForCost,true); });

test("ExecutiveBudget V3.5 classifica sobrado e exige pendencia especifica",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:completeV32Project({type:"sobrado",floors:2,builtAreaM2:140}),geometry:completeV32Geometry({perimeterM:44,roofAreaM2:165}),officialBaseRows:officialRowsV34()}); assert.equal(result.typologyRouting.typology,"sobrado"); assert.ok(result.typologyRouting.pendencias.some((item)=>/escada|laje|sobrado/i.test(item.message))); assert.ok(result.etapas.some((stage)=>stage.id==="estrutura")); });

test("ExecutiveBudget V3.5 galpao metalico nao recebe loucas metais residenciais",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"galpao_metalico",city:"Vitoria da Conquista",state:"BA",builtAreaM2:300,floors:1,standard:"industrial",ceilingHeightM:6,structuralType:"estrutura metalica",roofType:"telha metalica",foundationType:"sapatas isoladas"},geometry:{perimeterM:70,wallThicknessM:0.12,roofSlopePercent:10,openingsAreaM2:30},officialBaseRows:officialRowsV34()}); const ids=disciplineIds(result); assert.equal(result.typologyRouting.typology,"galpao_metalico"); assert.ok(ids.includes("estrutura_metalica")); assert.ok(ids.includes("piso_industrial")); assert.ok(ids.includes("fechamento_metalico")); assert.ok(ids.includes("drenagem")); assert.equal(ids.includes("loucas"),false); assert.equal(ids.includes("metais"),false); assert.equal(result.typologyRouting.readyForCost,false); assert.equal(result.readyForCost,false); });

test("ExecutiveBudget V3.5 muro de arrimo nao recebe disciplinas de casa",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"muro_arrimo",city:"Salvador",state:"BA",builtAreaM2:24,floors:1,standard:"contencao",ceilingHeightM:3,structuralType:"concreto armado",roofType:"nao se aplica",foundationType:"sapata corrida"},geometry:{perimeterM:12,wallThicknessM:0.2,roofAreaM2:1,openingsAreaM2:0},officialBaseRows:officialRowsV34()}); const ids=disciplineIds(result); assert.equal(result.typologyRouting.typology,"muro_arrimo"); assert.ok(ids.includes("contencao")); assert.ok(ids.includes("drenagem")); assert.ok(ids.includes("impermeabilizacao")); assert.ok(ids.includes("reaterro")); assert.equal(ids.includes("loucas"),false); assert.equal(ids.includes("pintura"),false); assert.equal(result.readyForCost,false); });

test("ExecutiveBudget V3.5 reforma banheiro nao vira obra nova",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"reforma_banheiro",city:"Salvador",state:"BA",builtAreaM2:6,floors:1,standard:"medio",ceilingHeightM:2.6,structuralType:"nao se aplica",roofType:"nao se aplica",foundationType:"nao se aplica"},geometry:{perimeterM:10,wallThicknessM:0.12,roofAreaM2:1,openingsAreaM2:2},officialBaseRows:officialRowsV34()}); const ids=disciplineIds(result); assert.equal(result.typologyRouting.typology,"reforma_banheiro"); assert.ok(ids.includes("demolicao")); assert.ok(ids.includes("impermeabilizacao")); assert.ok(ids.includes("loucas")); assert.ok(ids.includes("metais")); assert.equal(ids.includes("fundacao"),false); assert.equal(ids.includes("cobertura"),false); assert.equal(result.readyForCost,false); });

test("ExecutiveBudget V3.5 ampliacao residencial usa disciplinas proprias",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"ampliacao_residencial",city:"Lauro de Freitas",state:"BA",builtAreaM2:35,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"concreto armado",roofType:"telha ceramica",foundationType:"sapata",blockType:"bloco ceramico"},geometry:{perimeterM:24,wallThicknessM:0.14,roofSlopePercent:25,openingsAreaM2:4},officialBaseRows:officialRowsV34()}); const ids=disciplineIds(result); assert.equal(result.typologyRouting.typology,"ampliacao_residencial"); assert.ok(ids.includes("compatibilizacao_existente")); assert.ok(ids.includes("fundacao_complementar")); assert.ok(ids.includes("estrutura")); assert.equal(result.readyForCost,false); });

test("ExecutiveBudget V3.5 tipologia desconhecida bloqueia disciplinas executivas",()=>{ const e=load(); const result=e.buildResidentialExecutiveBudget({project:{type:"obra especial",city:"Salvador",state:"BA",builtAreaM2:50,floors:1,standard:"medio",ceilingHeightM:2.8,structuralType:"misto",roofType:"especial",foundationType:"especial"},geometry:{perimeterM:30,wallThicknessM:0.14,roofAreaM2:60},officialBaseRows:officialRowsV34()}); assert.equal(result.typologyRouting.typology,"desconhecida"); assert.equal(result.etapas.length,0); assert.ok(result.typologyRouting.pendencias.length>0); assert.equal(result.readyForCost,false); });
